services:
  # Database - PostgreSQL
  postgres:
    image: postgres:15
    container_name: attendance-app-postgres
    environment:
      POSTGRES_DB: learning-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance-app-network
    restart: unless-stopped

  # Redis for queues and caching
  redis:
    image: redis:7-alpine
    container_name: attendance-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - attendance-app-network
    restart: unless-stopped

  # MinIO for file storage (S3-compatible)
  minio:
    image: minio/minio:latest
    container_name: attendance-app-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    networks:
      - attendance-app-network
    restart: unless-stopped

  # n8n for workflow automation (email sending)
  n8n:
    image: n8nio/n8n:latest
    container_name: attendance-app-n8n
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_HOST: n8n
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      # WEBHOOK_URL: http://localhost:5678
      WEBHOOK_URL: https://n8n.attendance-app.io.vn
      GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
      N8N_DATABASE_TYPE: postgresdb
      N8N_DATABASE_POSTGRESDB_HOST: postgres
      N8N_DATABASE_POSTGRESDB_PORT: 5432
      N8N_DATABASE_POSTGRESDB_DATABASE: n8n
      N8N_DATABASE_POSTGRESDB_USER: postgres
      N8N_DATABASE_POSTGRESDB_PASSWORD: 123456
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - attendance-app-network
    depends_on:
      - postgres
    restart: unless-stopped

  # Main NestJS application (tạm thời comment lại)
  # app:
  #   build: .
  #   container_name: attendance-app-backend
  #   ports:
  #     - "3010:3010"
  #   environment:
  #     # Database
  #     DATABASE_URL: postgresql://postgres:123456@postgres:5432/learning-api
  #     
  #     # Redis
  #     REDIS_URL: redis://redis:6379
  #     
  #     # MinIO
  #     MINIO_ENDPOINT: http://minio:9000
  #     MINIO_ACCESS_KEY: admin
  #     MINIO_SECRET_KEY: admin123
  #     MINIO_BUCKET: uploads
  #     
  #     # JWT
  #     JWT_SECRET: Anhleonard2022002
  #     JWT_EXPIRATION: 3600
  #     
  #     # n8n
  #     N8N_ENDPOINT: http://n8n:5678
  #     
  #     # Frontend
  #     FE_ENDPOINT: http://localhost:3015
  #     
  #     # App
  #     PORT: 3010
  #     NODE_ENV: development
  #   volumes:
  #     - ./uploads:/app/uploads
  #   networks:
  #     - attendance-app-network
  #   depends_on:
  #     - postgres
  #     - redis
  #     - minio
  #     - n8n
  #   restart: unless-stopped

networks:
  attendance-app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  n8n_data:
    driver: local 