filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/app/logs/*.log"
    # Remove JSON parsing since we're now using plain text logs
    multiline.pattern: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
    multiline.negate: true
    multiline.match: after
    scan_frequency: 10s

processors:
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

setup.ilm.enabled: false
setup.template.enabled: false

logging.level: info
logging.to_stderr: true
