"use client";
import "./globals.css";
import { useEffect } from "react";
import localFont from "next/font/local";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "@/redux/store";
import Modal from "@/components/modal";
import Drawer from "@/lib/drawer";
import ConfirmModal from "@/components/confirm-modal";
import Loading from "@/lib/loading";
import { Alert } from "@/components/alert";
// import { Ysabeau_Office } from "next/font/google";
import { Source_Sans_3 } from "next/font/google";

const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-source-sans-3",
});

const Urbanist = localFont({
  src: [
    { path: "../assets/fonts/Urbanist-Thin.ttf", weight: "100" },
    { path: "../assets/fonts/Urbanist-ExtraLight.ttf", weight: "200" },
    { path: "../assets/fonts/Urbanist-Light.ttf", weight: "300" },
    { path: "../assets/fonts/Urbanist-Regular.ttf", weight: "400" },
    { path: "../assets/fonts/Urbanist-Medium.ttf", weight: "500" },
    { path: "../assets/fonts/Urbanist-SemiBold.ttf", weight: "600" },
    { path: "../assets/fonts/Urbanist-Bold.ttf", weight: "700" },
    { path: "../assets/fonts/Urbanist-ExtraBold.ttf", weight: "800" },
    { path: "../assets/fonts/Urbanist-Black.ttf", weight: "900" },
  ],
});

const Questrial = localFont({
  src: [
    {
      // path: "../assets/fonts/SFUFuturaBook.woff2",
      path: "../assets/fonts/Questrial-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-questrial",
});

// export const metadata: Metadata = {
//   title: "Learning App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${sourceSans3.className} ${sourceSans3.variable}`}>
      <body suppressHydrationWarning className="font-normal">
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <div>{children}</div>
            <Modal />
            <Drawer />
            <ConfirmModal />
            <Loading />
            <Alert />
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
